part of 'expense_models.dart';

final expenseDemoToday = DateUtils.dateOnly(DateTime.now());

final demoExpenses = <ExpenseRecord>[
  ExpenseRecord(
    id: 'EXP-1048',
    vendor: 'Central Supply',
    category: ExpenseCategory.materials,
    amount: 231.50,
    date: expenseDemoToday,
    owner: 'Alex Morgan',
    paidByEmployeeId: 'alex',
    job: 'JOB-1038 · Replace kitchen faucet',
    jobId: 'job-1038',
    receiptStatus: 'Receipt reviewed',
    receiptType: ExpenseReceiptType.detailed,
    receiptImageCount: 1,
    receiptSubtotal: 213.86,
    salesTax: 17.64,
    lineItems: [
      ExpenseLineItem(
        id: 'EXP-1048-L1',
        description: 'Single-handle pull-down kitchen faucet',
        partNumber: 'KPF-1610',
        category: ExpenseCategory.materials,
        quantity: 1,
        unit: 'each',
        unitPrice: 89,
        jobId: 'job-1038',
        jobLabel: 'JOB-1038 · Replace kitchen faucet',
      ),
      ExpenseLineItem(
        id: 'EXP-1048-L2',
        description: '20-in braided stainless faucet connector',
        category: ExpenseCategory.materials,
        quantity: 2,
        unit: 'each',
        unitPrice: 12.49,
        jobId: 'job-1038',
        jobLabel: 'JOB-1038 · Replace kitchen faucet',
      ),
      ExpenseLineItem(
        id: 'EXP-1048-L3',
        description: "Plumber's putty",
        category: ExpenseCategory.materials,
        quantity: 1,
        unit: 'each',
        unitPrice: 8.89,
        jobId: 'job-1038',
        jobLabel: 'JOB-1038 · Replace kitchen faucet',
      ),
      ExpenseLineItem(
        id: 'EXP-1048-L4',
        description: '1/2-in compression quarter-turn angle stop',
        category: ExpenseCategory.materials,
        quantity: 2,
        unit: 'each',
        unitPrice: 43,
        jobId: 'job-1038',
        jobLabel: 'JOB-1038 · Replace kitchen faucet',
      ),
      ExpenseLineItem(
        id: 'EXP-1048-L5',
        description: 'Thread seal tape',
        category: ExpenseCategory.materials,
        quantity: 1,
        unit: 'roll',
        unitPrice: 4.99,
        jobId: 'job-1038',
        jobLabel: 'JOB-1038 · Replace kitchen faucet',
      ),
    ],
  ),
  ExpenseRecord(
    id: 'EXP-1047',
    vendor: 'QuickFuel',
    category: ExpenseCategory.fuel,
    amount: 64.72,
    date: expenseDemoToday,
    owner: 'Alex Morgan',
    paidByEmployeeId: 'alex',
    receiptStatus: 'Receipt confirmed',
    receiptType: ExpenseReceiptType.basic,
    receiptImageCount: 1,
    approvalStatus: ExpenseApprovalStatus.pending,
    approvalReason:
        "This purchase is above Alex Morgan's \$50 field-expense limit.",
  ),
  ExpenseRecord(
    id: 'EXP-1049',
    vendor: 'Local Hardware',
    category: ExpenseCategory.tools,
    amount: 28.19,
    date: expenseDemoToday,
    owner: 'Alex Morgan',
    paidByEmployeeId: 'alex',
    receiptStatus: 'Receipt details unfinished',
    receiptType: ExpenseReceiptType.detailed,
    receiptImageCount: 1,
    requiresSubmitterAttention: true,
    submitterAttentionReason:
        'Finish the detailed receipt lines before submitting this expense.',
  ),
  ExpenseRecord(
    id: 'EXP-1050',
    vendor: 'City Parking',
    category: ExpenseCategory.travel,
    amount: 12.00,
    date: expenseDemoToday,
    owner: 'Alex Morgan',
    paidByEmployeeId: 'alex',
    job: 'JOB-1041 · Office lighting repair',
    jobId: 'job-1041',
    receiptStatus: 'Receipt attached',
  ),
  ExpenseRecord(
    id: 'EXP-1051',
    vendor: 'CleanPro Wholesale',
    category: ExpenseCategory.consumables,
    amount: 46.35,
    date: expenseDemoToday,
    owner: 'Jordan Lee',
    paidByEmployeeId: 'jordan',
    job: 'JOB-1034 · Move-out cleaning',
    jobId: 'job-1034',
    receiptStatus: 'Receipt attached',
  ),
  ExpenseRecord(
    id: 'EXP-1046',
    vendor: 'CleanPro Wholesale',
    category: ExpenseCategory.consumables,
    amount: 38.40,
    date: expenseDemoToday.subtract(const Duration(days: 1)),
    owner: 'Jordan Lee',
    paidByEmployeeId: 'jordan',
    job: 'JOB-1034 · Move-out cleaning',
    jobId: 'job-1034',
    receiptStatus: 'Receipt attached',
  ),
  ExpenseRecord(
    id: 'EXP-1045',
    vendor: 'Regional Materials Order',
    category: ExpenseCategory.materials,
    amount: 4588.50,
    date: DateTime(expenseDemoToday.year, expenseDemoToday.month, 7),
    owner: 'Alex Morgan',
    paidByEmployeeId: 'alex',
    receiptStatus: 'Receipt reviewed',
  ),
  ExpenseRecord(
    id: 'EXP-1042',
    vendor: 'Tool Rental Center',
    category: ExpenseCategory.tools,
    amount: 92.00,
    date: expenseDemoToday.subtract(const Duration(days: 2)),
    owner: 'Alex Morgan',
    paidByEmployeeId: 'alex',
    job: 'JOB-1040 · Drain line repair',
    jobId: 'job-1040',
    receiptStatus: 'Receipt attached',
  ),
  ExpenseRecord(
    id: 'EXP-1041',
    vendor: 'Metro Mobile',
    category: ExpenseCategory.phoneInternet,
    amount: 86.00,
    date: expenseDemoToday.subtract(const Duration(days: 4)),
    owner: 'Alex Morgan',
    paidByEmployeeId: 'alex',
    receiptStatus: 'Receipt attached',
  ),
  ExpenseRecord(
    id: 'EXP-1040',
    vendor: 'County Permit Office',
    category: ExpenseCategory.licensesTaxes,
    amount: 125.00,
    date: expenseDemoToday.subtract(const Duration(days: 6)),
    owner: 'Alex Morgan',
    paidByEmployeeId: 'alex',
    job: 'JOB-1037 · Water heater replacement',
    jobId: 'job-1037',
    receiptStatus: 'Receipt attached',
  ),
  ExpenseRecord(
    id: 'EXP-1044',
    vendor: 'Fleet Fuel and Service',
    category: ExpenseCategory.vehicleRepair,
    amount: 1679.28,
    date: DateTime(expenseDemoToday.year, expenseDemoToday.month, 13),
    owner: 'Jordan Lee',
    paidByEmployeeId: 'jordan',
    receiptStatus: 'Receipt reviewed',
  ),
  ExpenseRecord(
    id: 'EXP-1043',
    vendor: 'Business Services Group',
    category: ExpenseCategory.office,
    amount: 1809.60,
    date: DateTime(expenseDemoToday.year, expenseDemoToday.month, 19),
    owner: 'Alex Morgan',
    paidByEmployeeId: 'alex',
    receiptStatus: 'Receipt reviewed',
  ),
];

final demoExpenseReceiptDrafts = <ExpenseReceiptDraft>[
  ExpenseReceiptDraft(
    id: 'receipt-draft-1',
    title: 'Supply house receipt',
    expenseDate: expenseDemoToday,
    updatedOn: expenseDemoToday,
    ownerEmployeeId: 'alex',
    owner: 'Alex Morgan',
    imageCount: 2,
  ),
  ExpenseReceiptDraft(
    id: 'receipt-draft-2',
    title: 'Fuel receipt',
    expenseDate: expenseDemoToday.subtract(const Duration(days: 1)),
    updatedOn: expenseDemoToday.subtract(const Duration(days: 1)),
    ownerEmployeeId: 'alex',
    owner: 'Alex Morgan',
    imageCount: 1,
  ),
];

final demoScheduledExpenses = <ScheduledExpenseRecord>[
  ScheduledExpenseRecord(
    id: 'scheduled-expense-1',
    title: 'Commercial vehicle insurance',
    category: ExpenseCategory.vehicleInsurance,
    amount: 418.00,
    nextDueOn: expenseDemoToday.add(const Duration(days: 3)),
    kind: ExpenseScheduleKind.monthly,
    ownerEmployeeId: 'alex',
    owner: 'Alex Morgan',
    reminderDaysBefore: [7, 3, 1],
    dueDay: 4,
    receiptRequired: true,
  ),
  ScheduledExpenseRecord(
    id: 'scheduled-expense-2',
    title: 'Business software subscription',
    category: ExpenseCategory.office,
    amount: 39.00,
    nextDueOn: DateTime(expenseDemoToday.year, expenseDemoToday.month + 1, 5),
    kind: ExpenseScheduleKind.monthly,
    ownerEmployeeId: 'alex',
    owner: 'Alex Morgan',
    reminderDaysBefore: [3, 1],
    dueDay: 5,
  ),
];
