"""Exhaustive artifact reconciliation, explicitly NOT semantic acceptance."""
import argparse
from collections import Counter
import gzip
import hashlib
import json
from pathlib import Path
import sqlite3
import tempfile


def digest(value):
    return hashlib.sha256(json.dumps(value, sort_keys=True,
                                    ensure_ascii=False).encode()).hexdigest()


def audit(workspace, output):
    output.mkdir(parents=True, exist_ok=True)
    expected = {'electrical': 902, 'plumbing': 1153, 'hvac': 1279}
    records, issues, ids, totals = [], [], [], {}
    artifact = workspace / 'assets/inventory/core_catalog.sqlite.gz'
    with tempfile.TemporaryDirectory() as temporary:
        dbpath = Path(temporary) / 'catalog.sqlite'
        dbpath.write_bytes(gzip.decompress(artifact.read_bytes()))
        db = sqlite3.connect(f'file:{dbpath}?mode=ro', uri=True)
        try:
            integrity = db.execute('pragma integrity_check').fetchall()
            if integrity != [('ok',)]:
                issues.append({'kind': 'sqlite_integrity', 'details': integrity})
            rows = db.execute('select id,payload from catalog_items').fetchall()
            by_id = {}
            for key, payload in rows:
                by_id.setdefault(key, []).append(json.loads(payload))
            for trade, count in expected.items():
                source = workspace / f'assets/inventory/{trade}_core.json.gz'
                pack = json.loads(gzip.decompress(source.read_bytes()))
                totals[trade] = len(pack['items'])
                if totals[trade] != count:
                    issues.append({'kind': 'population', 'trade': trade,
                                   'expected': count, 'actual': totals[trade]})
                for index, item in enumerate(pack['items']):
                    identity = item.get('id')
                    ids.append(identity)
                    matches = by_id.get(identity, [])
                    equal = len(matches) == 1 and matches[0] == item
                    if not equal:
                        issues.append({'kind': 'payload_mismatch', 'id': identity})
                    if item.get('trade', '').lower() != trade:
                        issues.append({'kind': 'trade_mismatch', 'id': identity})
                    records.append({
                        'trade': trade, 'id': identity, 'sourceIndex': index,
                        'sourceArtifact': str(source.relative_to(workspace)),
                        'sourceArtifactSha256': hashlib.sha256(source.read_bytes()).hexdigest(),
                        'payloadSha256': digest(item),
                        'sqlitePayloadEqual': equal,
                        'fieldEvidence': {name: {'valueSha256': digest(value),
                                                'acceptance': 'unverified',
                                                'authoritativeEvidence': []}
                                          for name, value in item.items()},
                        'semanticAcceptance': 'unverified',
                        'reason': 'Legacy/export agreement is not independent field evidence',
                        'generatedMetadata': item.get('intelligence', {}).get('autoGenerated'),
                        'legacyVerifiedManually': item.get('intelligence', {}).get('verifiedManually'),
                    })
            for identity, count in Counter(ids).items():
                if count != 1:
                    issues.append({'kind': 'duplicate_export_identity', 'id': identity, 'count': count})
            for identity in sorted(set(by_id) - set(ids)):
                issues.append({'kind': 'unexplained_sqlite_record', 'id': identity})
        finally:
            db.close()
    browse = workspace / 'assets/inventory/browse_batch.sqlite'
    db = sqlite3.connect(f'file:{browse}?mode=ro', uri=True)
    try:
        browse_count = db.execute('select count(*) from items').fetchone()[0]
        trades = [row[0] for row in db.execute('select name from trades order by name')]
    finally:
        db.close()
    summary = {'scope': 'All records and payload fields compared; no sampling',
               'referenceCounts': totals, 'referenceTotal': len(records),
               'sqliteRows': len(rows), 'structuralDiscrepancies': issues,
               'semanticAcceptedRecords': 0, 'semanticUnverifiedRecords': len(records),
               'runtimeBrowseItems': browse_count, 'runtimeTrades': trades,
               'catalogAcceptance': 'NOT ACCEPTED',
               'limitation': 'No independent semantic/product/translation evidence supplied by this comparison'}
    (output / 'catalog_reconciliation.json').write_text(json.dumps(summary, indent=2)+'\n')
    data = ''.join(json.dumps(r, ensure_ascii=False, sort_keys=True)+'\n' for r in records)
    (output / 'catalog_record_evidence.jsonl.gz').write_bytes(gzip.compress(data.encode(), mtime=0))
    print(json.dumps(summary, indent=2))


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--output', type=Path, required=True)
    args = parser.parse_args()
    audit(Path(__file__).resolve().parents[2], args.output)
