import 'dart:async';
import 'package:flutter/material.dart';
import 'package:pdfx/pdfx.dart';

/// One reader for retained uploads and generated bytes. The feature authorizes
/// access before supplying the open callback; this reader never exports files.
class PdfDocumentView extends StatefulWidget {
  const PdfDocumentView({required this.open, super.key});
  final Future<PdfDocument> Function() open;
  @override
  State<PdfDocumentView> createState() => _PdfDocumentViewState();
}

class _PdfDocumentViewState extends State<PdfDocumentView> {
  late final Future<PdfDocument> _document = widget.open();
  late final PdfControllerPinch _controller = PdfControllerPinch(
    document: _document,
  );
  int _page = 1;
  int? _pages;
  @override
  void dispose() {
    _controller.dispose();
    unawaited(_document.then<void>((d) => d.close(), onError: (_) {}));
    super.dispose();
  }

  @override
  Widget build(BuildContext context) => Column(
    children: [
      Expanded(
        child: PdfViewPinch(
          controller: _controller,
          builders: PdfViewPinchBuilders<DefaultBuilderOptions>(
            options: const DefaultBuilderOptions(),
            documentLoaderBuilder: (_) =>
                const Center(child: CircularProgressIndicator()),
            pageLoaderBuilder: (_) =>
                const Center(child: CircularProgressIndicator()),
            errorBuilder: (_, _) => const Center(
              child: Padding(
                padding: EdgeInsets.all(16),
                child: Text(
                  'This PDF could not be opened. It may be missing, damaged, or protected. Your saved information is unchanged.',
                ),
              ),
            ),
          ),
          onDocumentLoaded: (d) {
            if (mounted) setState(() => _pages = d.pagesCount);
          },
          onPageChanged: (p) {
            if (mounted) setState(() => _page = p);
          },
        ),
      ),
      if ((_pages ?? 0) > 1)
        Material(
          color: Theme.of(context).colorScheme.surfaceContainerHigh,
          child: Padding(
            padding: const EdgeInsets.all(6),
            child: Row(
              mainAxisSize: MainAxisSize.min,
              children: [
                IconButton(
                  tooltip: 'Previous page',
                  onPressed: _page <= 1
                      ? null
                      : () => _controller.previousPage(
                          duration: const Duration(milliseconds: 180),
                          curve: Curves.easeOut,
                        ),
                  icon: const Icon(Icons.chevron_left),
                ),
                Expanded(
                  child: Text(
                    'Page $_page of $_pages',
                    textAlign: TextAlign.center,
                  ),
                ),
                IconButton(
                  tooltip: 'Next page',
                  onPressed: _page >= _pages!
                      ? null
                      : () => _controller.nextPage(
                          duration: const Duration(milliseconds: 180),
                          curve: Curves.easeOut,
                        ),
                  icon: const Icon(Icons.chevron_right),
                ),
              ],
            ),
          ),
        ),
    ],
  );
}
